// ═══════════════════════════════════════════════════════════
//  داده‌های نمونه برای نمایش
//  Vira Decimal Abacus - Sample/Demo Data
// ═══════════════════════════════════════════════════════════

import type { Lead, Student, Referral, Exam, ExamQuestion } from '@/types';
import { generateReferralCode } from './referral';

// ─── Sample Leads ─────────────────────────────────────────

export const sampleLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'مریم کریمی',
    phone: '09121234567',
    email: 'maryam@example.com',
    childName: 'سارا کریمی',
    childAge: 7,
    interestedCourse: 'دوره چرتکه مقدماتی',
    source: 'website_form',
    status: 'new',
    priority: 'high',
    notes: 'از طریق فرم وبسایت ثبت‌نام کرده، علاقه‌مند به کلاس حضوری',
    createdAt: '2024-12-01T10:30:00Z',
    updatedAt: '2024-12-01T10:30:00Z',
  },
  {
    id: 'lead-2',
    name: 'علی حسینی',
    phone: '09132345678',
    childName: 'محمدحسین حسینی',
    childAge: 9,
    interestedCourse: 'دوره حساب ذهنی متوسط',
    source: 'whatsapp',
    status: 'contacted',
    priority: 'medium',
    notes: 'تماس اول گرفته شد، مشاوره فردا ساعت ۱۶',
    createdAt: '2024-11-28T14:15:00Z',
    updatedAt: '2024-11-29T09:00:00Z',
  },
  {
    id: 'lead-3',
    name: 'فاطمه رضایی',
    phone: '09143456789',
    childName: 'امیرعلی رضایی',
    childAge: 6,
    interestedCourse: 'دوره چرتکه مقدماتی',
    source: 'instagram',
    status: 'consultation_scheduled',
    priority: 'high',
    notes: 'مشاوره آنلاین برنامه‌ریزی شده برای شنبه',
    createdAt: '2024-11-25T11:45:00Z',
    updatedAt: '2024-11-27T16:00:00Z',
  },
  {
    id: 'lead-4',
    name: 'زهرا محمدی',
    phone: '09154567890',
    childName: 'آریا محمدی',
    childAge: 10,
    interestedCourse: 'دوره چرتکه پیشرفته',
    source: 'referral',
    status: 'trial_class_done',
    priority: 'high',
    notes: 'کد معرف: VIRA-A3K9، کلاس آزمایشی شرکت کرده و راضی بوده',
    referralCode: 'VIRA-A3K9',
    createdAt: '2024-11-20T08:30:00Z',
    updatedAt: '2024-11-26T17:30:00Z',
  },
  {
    id: 'lead-5',
    name: 'محمد نوری',
    phone: '09165678901',
    childName: 'فاطمه نوری',
    childAge: 8,
    interestedCourse: 'دوره حساب ذهنی متوسط',
    source: 'phone_call',
    status: 'enrolled',
    priority: 'medium',
    notes: 'ثبت‌نام قطعی انجام شد',
    createdAt: '2024-11-15T13:00:00Z',
    updatedAt: '2024-11-22T10:00:00Z',
  },
  {
    id: 'lead-6',
    name: 'سمیرا احمدی',
    phone: '09176789012',
    childName: 'رادیا احمدی',
    childAge: 5,
    interestedCourse: 'دوره چرتکه مقدماتی',
    source: 'telegram',
    status: 'consultation_done',
    priority: 'medium',
    notes: 'مشاوره انجام شد، در انتظار تصمیم والدین',
    createdAt: '2024-11-10T09:15:00Z',
    updatedAt: '2024-11-18T14:30:00Z',
  },
  {
    id: 'lead-7',
    name: 'رضا صادقی',
    phone: '09187890123',
    childName: 'مهسا صادقی',
    childAge: 12,
    interestedCourse: 'دوره آمادگی مسابقات',
    source: 'walk_in',
    status: 'enrollment_offered',
    priority: 'urgent',
    notes: 'مراجعه حضوری، بسیار علاقه‌مند، تخفیف ویژه پیشنهاد شد',
    createdAt: '2024-11-05T16:45:00Z',
    updatedAt: '2024-11-12T11:00:00Z',
  },
  {
    id: 'lead-8',
    name: 'نازنین کاظمی',
    phone: '09198901234',
    childName: 'کیان کاظمی',
    childAge: 7,
    interestedCourse: 'دوره چرتکه مقدماتی',
    source: 'advertisement',
    status: 'new',
    priority: 'low',
    notes: 'از طریق تبلیغ اینستاگرام',
    createdAt: '2024-12-02T07:20:00Z',
    updatedAt: '2024-12-02T07:20:00Z',
  },
  {
    id: 'lead-9',
    name: 'حسین عباسی',
    phone: '09209012345',
    childName: 'الناز عباسی',
    childAge: 11,
    interestedCourse: 'دوره چرتکه پیشرفته',
    source: 'referral',
    status: 'contacted',
    priority: 'medium',
    referralCode: 'VIRA-B7M2',
    notes: 'کد معرف: VIRA-B7M2، تماس اول گرفته شد',
    createdAt: '2024-11-30T12:00:00Z',
    updatedAt: '2024-12-01T15:00:00Z',
  },
  {
    id: 'lead-10',
    name: 'لیلا جعفری',
    phone: '09210123456',
    childName: 'پارسا جعفری',
    childAge: 9,
    interestedCourse: 'دوره حساب ذهنی متوسط',
    source: 'website_form',
    status: 'lost',
    priority: 'low',
    notes: 'به دلیل برنامه‌های متناقض انصراف داد',
    createdAt: '2024-10-20T10:00:00Z',
    updatedAt: '2024-11-05T08:30:00Z',
  },
];

// ─── Sample Students ──────────────────────────────────────

export const sampleStudents: Student[] = [
  {
    id: 'stu-1',
    name: 'سارینا محمدی',
    phone: '09121111111',
    role: 'student',
    parentName: 'سمیرا محمدی',
    age: 8,
    level: 'intermediate',
    enrolledCourses: ['2'],
    referralCode: 'VIRA-S1R4',
    createdAt: '2024-06-15T10:00:00Z',
    updatedAt: '2024-11-20T14:00:00Z',
  },
  {
    id: 'stu-2',
    name: 'امیرعلی کریمی',
    phone: '09132222222',
    role: 'student',
    parentName: 'رضا کریمی',
    age: 10,
    level: 'advanced',
    enrolledCourses: ['3'],
    referralCode: 'VIRA-K2E7',
    referredBy: 'VIRA-S1R4',
    createdAt: '2024-05-10T08:00:00Z',
    updatedAt: '2024-11-18T09:00:00Z',
  },
  {
    id: 'stu-3',
    name: 'آریا احمدی',
    phone: '09143333333',
    role: 'student',
    parentName: 'نازنین احمدی',
    age: 6,
    level: 'beginner',
    enrolledCourses: ['1'],
    referralCode: 'VIRA-A3K9',
    createdAt: '2024-09-01T12:00:00Z',
    updatedAt: '2024-11-25T16:00:00Z',
  },
  {
    id: 'stu-4',
    name: 'فاطمه حسینی',
    phone: '09154444444',
    role: 'student',
    parentName: 'مهدی حسینی',
    age: 12,
    level: 'competition',
    enrolledCourses: ['4', '3'],
    referralCode: 'VIRA-H4T1',
    createdAt: '2024-03-20T14:00:00Z',
    updatedAt: '2024-11-22T11:00:00Z',
  },
  {
    id: 'stu-5',
    name: 'مهدی رضایی',
    phone: '09165555555',
    role: 'student',
    parentName: 'زهرا رضایی',
    age: 7,
    level: 'beginner',
    enrolledCourses: ['1'],
    referralCode: 'VIRA-R5N8',
    createdAt: '2024-10-05T09:30:00Z',
    updatedAt: '2024-11-28T10:00:00Z',
  },
  {
    id: 'stu-6',
    name: 'رادیا صادقی',
    phone: '09176666666',
    role: 'student',
    parentName: 'پویا صادقی',
    age: 9,
    level: 'intermediate',
    enrolledCourses: ['2'],
    referralCode: 'VIRA-D6P3',
    createdAt: '2024-07-12T11:00:00Z',
    updatedAt: '2024-11-15T13:00:00Z',
  },
  {
    id: 'stu-7',
    name: 'کیان نوری',
    phone: '09187777777',
    role: 'student',
    parentName: 'فاطمه نوری',
    age: 8,
    level: 'intermediate',
    enrolledCourses: ['2'],
    referralCode: 'VIRA-N7Q6',
    referredBy: 'VIRA-S1R4',
    createdAt: '2024-08-20T15:00:00Z',
    updatedAt: '2024-11-10T09:00:00Z',
  },
  {
    id: 'stu-8',
    name: 'الناز عباسی',
    phone: '09198888888',
    role: 'student',
    parentName: 'حسین عباسی',
    age: 11,
    level: 'advanced',
    enrolledCourses: ['3', '4'],
    referralCode: 'VIRA-B7M2',
    createdAt: '2024-04-10T10:00:00Z',
    updatedAt: '2024-11-05T17:00:00Z',
  },
];

// ─── Sample Referrals ─────────────────────────────────────

export const sampleReferrals: Referral[] = [
  {
    id: 'ref-1',
    referrerCode: 'VIRA-S1R4',
    referrerId: 'stu-1',
    referrerName: 'سارینا محمدی',
    referredId: 'stu-2',
    referredName: 'امیرعلی کریمی',
    referredPhone: '09132222222',
    status: 'reward_claimed',
    reward: {
      type: 'discount_percentage',
      referrerValue: 10,
      referredValue: 10,
      referrerDescription: '۱۰٪ تخفیف شهریه',
      referredDescription: '۱۰٪ تخفیف شهریه',
    },
    courseEnrolled: '3',
    createdAt: '2024-05-05T10:00:00Z',
    convertedAt: '2024-05-10T08:00:00Z',
    rewardClaimedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: 'ref-2',
    referrerCode: 'VIRA-S1R4',
    referrerId: 'stu-1',
    referrerName: 'سارینا محمدی',
    referredId: 'stu-7',
    referredName: 'کیان نوری',
    referredPhone: '09187777777',
    status: 'enrolled',
    reward: {
      type: 'discount_percentage',
      referrerValue: 10,
      referredValue: 10,
      referrerDescription: '۱۰٪ تخفیف شهریه',
      referredDescription: '۱۰٪ تخفیف شهریه',
    },
    courseEnrolled: '2',
    createdAt: '2024-08-15T09:00:00Z',
    convertedAt: '2024-08-20T15:00:00Z',
  },
  {
    id: 'ref-3',
    referrerCode: 'VIRA-A3K9',
    referrerId: 'stu-3',
    referrerName: 'آریا احمدی',
    referredId: 'lead-4',
    referredName: 'آریا محمدی (مشتری)',
    referredPhone: '09154567890',
    status: 'trial_done',
    reward: {
      type: 'free_session',
      referrerValue: 1,
      referredValue: 1,
      referrerDescription: 'یک جلسه رایگان',
      referredDescription: 'یک جلسه رایگان',
    },
    createdAt: '2024-11-18T08:00:00Z',
    convertedAt: '2024-11-26T17:00:00Z',
  },
  {
    id: 'ref-4',
    referrerCode: 'VIRA-H4T1',
    referrerId: 'stu-4',
    referrerName: 'فاطمه حسینی',
    referredId: 'lead-9',
    referredName: 'الناز عباسی (مشتری)',
    referredPhone: '09209012345',
    status: 'registered',
    reward: {
      type: 'discount_fixed',
      referrerValue: 200000,
      referredValue: 200000,
      referrerDescription: '۲۰۰,۰۰۰ تومان تخفیف',
      referredDescription: '۲۰۰,۰۰۰ تومان تخفیف',
    },
    createdAt: '2024-11-28T12:00:00Z',
  },
  {
    id: 'ref-5',
    referrerCode: 'VIRA-D6P3',
    referrerId: 'stu-6',
    referrerName: 'رادیا صادقی',
    referredId: 'lead-new-1',
    referredName: 'نیما فرهادی',
    referredPhone: '09234567890',
    status: 'consultation',
    reward: {
      type: 'discount_percentage',
      referrerValue: 15,
      referredValue: 10,
      referrerDescription: '۱۵٪ تخفیف شهریه',
      referredDescription: '۱۰٪ تخفیف شهریه',
    },
    createdAt: '2024-11-22T14:00:00Z',
    convertedAt: '2024-11-25T10:00:00Z',
  },
  {
    id: 'ref-6',
    referrerCode: 'VIRA-K2E7',
    referrerId: 'stu-2',
    referrerName: 'امیرعلی کریمی',
    referredId: 'lead-expired-1',
    referredName: 'سینا رحیمی',
    referredPhone: '09245678901',
    status: 'expired',
    reward: {
      type: 'discount_percentage',
      referrerValue: 10,
      referredValue: 10,
      referrerDescription: '۱۰٪ تخفیف شهریه',
      referredDescription: '۱۰٪ تخفیف شهریه',
    },
    createdAt: '2024-09-01T10:00:00Z',
  },
];

// ─── Sample Exam Questions ────────────────────────────────

export const placementQuestions: ExamQuestion[] = [
  // Mental Addition
  {
    id: 'pq-1',
    type: 'mental_calculation',
    question: 'حاصل ۲۳ + ۴۵ چیست؟',
    options: [
      { id: 'a', text: '۶۸', isCorrect: true },
      { id: 'b', text: '۶۶', isCorrect: false },
      { id: 'c', text: '۷۸', isCorrect: false },
      { id: 'd', text: '۵۸', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'addition',
    explanation: '۲۳ + ۴۵ = ۶۸. ابتدا دهگان‌ها (۲۰ + ۴۰ = ۶۰) و سپس یکان‌ها (۳ + ۵ = ۸) را جمع می‌کنیم.',
  },
  {
    id: 'pq-2',
    type: 'mental_calculation',
    question: 'حاصل ۱۵۶ + ۲۴۳ چیست؟',
    options: [
      { id: 'a', text: '۳۹۹', isCorrect: true },
      { id: 'b', text: '۴۰۹', isCorrect: false },
      { id: 'c', text: '۳۸۹', isCorrect: false },
      { id: 'd', text: '۴۹۹', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'addition',
    explanation: '۱۵۶ + ۲۴۳ = ۳۹۹. از راست به چپ: ۶+۳=۹، ۵+۴=۹، ۱+۲=۳.',
  },
  // Mental Subtraction
  {
    id: 'pq-3',
    type: 'mental_calculation',
    question: 'حاصل ۸۵ - ۳۲ چیست؟',
    options: [
      { id: 'a', text: '۵۳', isCorrect: true },
      { id: 'b', text: '۵۷', isCorrect: false },
      { id: 'c', text: '۴۳', isCorrect: false },
      { id: 'd', text: '۶۳', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'subtraction',
    explanation: '۸۵ - ۳۲ = ۵۳. دهگان‌ها: ۸۰-۳۰=۵۰، یکان‌ها: ۵-۲=۳.',
  },
  {
    id: 'pq-4',
    type: 'mental_calculation',
    question: 'حاصل ۵۰۰ - ۱۸۷ چیست؟',
    options: [
      { id: 'a', text: '۳۱۳', isCorrect: true },
      { id: 'b', text: '۳۲۳', isCorrect: false },
      { id: 'c', text: '۳۰۳', isCorrect: false },
      { id: 'd', text: '۴۱۳', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'subtraction',
    explanation: '۵۰۰ - ۱۸۷ = ۳۱۳. ابتدا ۵۰۰-۲۰۰=۳۰۰، سپس ۳۰۰+۱۳=۳۱۳.',
  },
  // Abacus Reading
  {
    id: 'pq-5',
    type: 'abacus_reading',
    question: 'اگر مهره‌های چرتکه در میله یکان ۳ مهره پایین بالا شده و میله دهگان ۵ مهره پایین بالا شده باشد، عدد نمایش داده شده چیست؟',
    options: [
      { id: 'a', text: '۵۳', isCorrect: true },
      { id: 'b', text: '۳۵', isCorrect: false },
      { id: 'c', text: '۸', isCorrect: false },
      { id: 'd', text: '۱۵', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'abacus_reading',
    explanation: 'در چرتکه دهگانی، میله دهگان عدد ۵ و میله یکان عدد ۳ را نشان می‌دهد. عدد = ۵۳.',
  },
  {
    id: 'pq-6',
    type: 'abacus_reading',
    question: 'در چرتکه دهگانی، اگر مهره بالایی (۵) در میله یکان فعال و ۲ مهره پایین هم فعال باشند، عدد میله یکان چند است؟',
    options: [
      { id: 'a', text: '۷', isCorrect: true },
      { id: 'b', text: '۵۲', isCorrect: false },
      { id: 'c', text: '۳', isCorrect: false },
      { id: 'd', text: '۲', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'abacus_reading',
    explanation: 'مهره بالایی = ۵، مهره‌های پایین = ۲. مجموع = ۵ + ۲ = ۷.',
  },
  {
    id: 'pq-7',
    type: 'abacus_reading',
    question: 'اگر در چرتکه، میله صدگان ۱ مهره پایین، میله دهگان ۳ مهره پایین و میله یکان مهره بالایی (۵) + ۱ مهره پایین فعال باشد، عدد چیست؟',
    options: [
      { id: 'a', text: '۱۳۶', isCorrect: true },
      { id: 'b', text: '۱۶۳', isCorrect: false },
      { id: 'c', text: '۶۳۱', isCorrect: false },
      { id: 'd', text: '۱۳۵', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'abacus_reading',
    explanation: 'صدگان=۱، دهگان=۳، یکان=۵+۱=۶. عدد = ۱۳۶.',
  },
  // Number Sequence
  {
    id: 'pq-8',
    type: 'number_sequence',
    question: 'عدد بعدی در دنباله ۲، ۵، ۸، ۱۱، ... چیست؟',
    options: [
      { id: 'a', text: '۱۴', isCorrect: true },
      { id: 'b', text: '۱۳', isCorrect: false },
      { id: 'c', text: '۱۵', isCorrect: false },
      { id: 'd', text: '۱۶', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'number_sequence',
    explanation: 'هر عدد ۳ واحد از قبلی بیشتر است: ۲+۳=۵، ۵+۳=۸، ۸+۳=۱۱، ۱۱+۳=۱۴.',
  },
  {
    id: 'pq-9',
    type: 'number_sequence',
    question: 'عدد بعدی در دنباله ۱، ۴، ۹، ۱۶، ۲۵، ... چیست؟',
    options: [
      { id: 'a', text: '۳۶', isCorrect: true },
      { id: 'b', text: '۳۰', isCorrect: false },
      { id: 'c', text: '۳۵', isCorrect: false },
      { id: 'd', text: '۴۹', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'number_sequence',
    explanation: 'اعداد مربع کامل هستند: ۱²، ۲²، ۳²، ۴²، ۵²، ۶²=۳۶.',
  },
  // Multiplication
  {
    id: 'pq-10',
    type: 'mental_calculation',
    question: 'حاصل ۶ × ۷ چیست؟',
    options: [
      { id: 'a', text: '۴۲', isCorrect: true },
      { id: 'b', text: '۴۸', isCorrect: false },
      { id: 'c', text: '۳۶', isCorrect: false },
      { id: 'd', text: '۴۹', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'multiplication',
    explanation: '۶ × ۷ = ۴۲. جدول ضرب ۶: ۶، ۱۲، ۱۸، ۲۴، ۳۰، ۳۶، ۴۲.',
  },
  {
    id: 'pq-11',
    type: 'mental_calculation',
    question: 'حاصل ۱۲ × ۴ چیست؟',
    options: [
      { id: 'a', text: '۴۸', isCorrect: true },
      { id: 'b', text: '۳۶', isCorrect: false },
      { id: 'c', text: '۵۲', isCorrect: false },
      { id: 'd', text: '۴۴', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'multiplication',
    explanation: '۱۲ × ۴ = ۴۸. (۱۰×۴=۴۰) + (۲×۴=۸) = ۴۸.',
  },
  // Mixed Operations
  {
    id: 'pq-12',
    type: 'mental_calculation',
    question: 'حاصل ۲۵ + ۳۰ - ۱۵ چیست؟',
    options: [
      { id: 'a', text: '۴۰', isCorrect: true },
      { id: 'b', text: '۵۰', isCorrect: false },
      { id: 'c', text: '۳۰', isCorrect: false },
      { id: 'd', text: '۴۵', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'mixed',
    explanation: '۲۵+۳۰=۵۵، سپس ۵۵-۱۵=۴۰.',
  },
  {
    id: 'pq-13',
    type: 'mental_calculation',
    question: 'حاصل ۸ × ۵ + ۱۲ چیست؟',
    options: [
      { id: 'a', text: '۵۲', isCorrect: true },
      { id: 'b', text: '۱۰۰', isCorrect: false },
      { id: 'c', text: '۴۶', isCorrect: false },
      { id: 'd', text: '۶۰', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'mixed',
    explanation: 'ابتدا ضرب: ۸×۵=۴۰، سپس جمع: ۴۰+۱۲=۵۲.',
  },
  // Advanced Questions
  {
    id: 'pq-14',
    type: 'mental_calculation',
    question: 'حاصل ۴۵ × ۳ چیست؟',
    options: [
      { id: 'a', text: '۱۳۵', isCorrect: true },
      { id: 'b', text: '۱۲۵', isCorrect: false },
      { id: 'c', text: '۱۴۵', isCorrect: false },
      { id: 'd', text: '۱۵۵', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'multiplication',
    explanation: '۴۵×۳ = (۴۰×۳=۱۲۰) + (۵×۳=۱۵) = ۱۳۵.',
  },
  {
    id: 'pq-15',
    type: 'mental_calculation',
    question: 'حاصل ۱۰۰۰ - ۳۵۶ چیست؟',
    options: [
      { id: 'a', text: '۶۴۴', isCorrect: true },
      { id: 'b', text: '۶۵۴', isCorrect: false },
      { id: 'c', text: '۷۴۴', isCorrect: false },
      { id: 'd', text: '۶۳۴', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'hard',
    category: 'subtraction',
    explanation: '۱۰۰۰-۳۵۶ = ۶۴۴. روش مکمل: ۹-۳=۶، ۹-۵=۴، ۱۰-۶=۴.',
  },
  // Abacus Operations
  {
    id: 'pq-16',
    type: 'abacus_reading',
    question: 'در چرتکه دهگانی، عدد ۹۹ را چگونه نشان می‌دهیم؟',
    options: [
      { id: 'a', text: 'مهره بالایی + ۴ مهره پایین در هر دو میله', isCorrect: true },
      { id: 'b', text: '۹ مهره پایین در هر میله', isCorrect: false },
      { id: 'c', text: 'فقط مهره بالایی در هر میله', isCorrect: false },
      { id: 'd', text: 'مهره بالایی + ۵ مهره پایین در هر میله', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'abacus_reading',
    explanation: 'عدد ۹ = مهره بالایی (۵) + ۴ مهره پایین (۴). پس ۹۹ در هر دو میله همین‌طور نمایش داده می‌شود.',
  },
  {
    id: 'pq-17',
    type: 'mental_calculation',
    question: 'حاصل ۳۶ + ۴۷ چیست؟',
    options: [
      { id: 'a', text: '۸۳', isCorrect: true },
      { id: 'b', text: '۷۳', isCorrect: false },
      { id: 'c', text: '۸۲', isCorrect: false },
      { id: 'd', text: '۹۳', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'addition',
    explanation: '۳۶+۴۷: ۶+۷=۱۳ (یکان ۳، دهگان ۱ اضافه)، ۳+۴+۱=۸. نتیجه: ۸۳.',
  },
  {
    id: 'pq-18',
    type: 'number_sequence',
    question: 'عدد بعدی در دنباله ۳، ۶، ۱۲، ۲۴، ... چیست؟',
    options: [
      { id: 'a', text: '۴۸', isCorrect: true },
      { id: 'b', text: '۳۶', isCorrect: false },
      { id: 'c', text: '۳۰', isCorrect: false },
      { id: 'd', text: '۴۲', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'medium',
    category: 'number_sequence',
    explanation: 'هر عدد دو برابر قبلی است: ۳×۲=۶، ۶×۲=۱۲، ۱۲×۲=۲۴، ۲۴×۲=۴۸.',
  },
  {
    id: 'pq-19',
    type: 'mental_calculation',
    question: 'اگر ۵ دسته مداد هر کدام ۸ عدد باشند، جمعاً چند مداد داریم؟',
    options: [
      { id: 'a', text: '۴۰', isCorrect: true },
      { id: 'b', text: '۴۵', isCorrect: false },
      { id: 'c', text: '۳۵', isCorrect: false },
      { id: 'd', text: '۱۳', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'multiplication',
    explanation: '۵ × ۸ = ۴۰. پنج دسته هشت‌تایی برابر ۴۰ مداد.',
  },
  {
    id: 'pq-20',
    type: 'mental_calculation',
    question: 'حاصل ۲۵۰ + ۳۷۵ چیست؟',
    options: [
      { id: 'a', text: '۶۲۵', isCorrect: true },
      { id: 'b', text: '۶۳۵', isCorrect: false },
      { id: 'c', text: '۵۲۵', isCorrect: false },
      { id: 'd', text: '۶۱۵', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'hard',
    category: 'addition',
    explanation: '۲۵۰+۳۷۵: ۰+۵=۵، ۵+۷=۱۲ (۲ می‌ماند، ۱ منتقل)، ۲+۳+۱=۶. نتیجه: ۶۲۵.',
  },
  {
    id: 'pq-21',
    type: 'abacus_reading',
    question: 'اگر در چرتکه، فقط مهره بالایی (۵) در میله یکان فعال باشد و همه میله‌های دیگر خالی باشند، عدد چیست؟',
    options: [
      { id: 'a', text: '۵', isCorrect: true },
      { id: 'b', text: '۱', isCorrect: false },
      { id: 'c', text: '۵۰', isCorrect: false },
      { id: 'd', text: '۱۰', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'abacus_reading',
    explanation: 'مهره بالایی در میله یکان = ۵. بقیه میله‌ها صفر هستند. عدد = ۵.',
  },
  {
    id: 'pq-22',
    type: 'mental_calculation',
    question: 'حاصل ۱۴۴ ÷ ۱۲ چیست؟',
    options: [
      { id: 'a', text: '۱۲', isCorrect: true },
      { id: 'b', text: '۱۴', isCorrect: false },
      { id: 'c', text: '۱۱', isCorrect: false },
      { id: 'd', text: '۱۳', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'hard',
    category: 'division',
    explanation: '۱۴۴ ÷ ۱۲ = ۱۲. زیرا ۱۲ × ۱۲ = ۱۴۴.',
  },
  {
    id: 'pq-23',
    type: 'mental_calculation',
    question: 'حاصل ۷ × ۸ چیست؟',
    options: [
      { id: 'a', text: '۵۶', isCorrect: true },
      { id: 'b', text: '۵۴', isCorrect: false },
      { id: 'c', text: '۴۸', isCorrect: false },
      { id: 'd', text: '۶۳', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'multiplication',
    explanation: '۷ × ۸ = ۵۶. یکی از مهم‌ترین جدول‌های ضرب.',
  },
  {
    id: 'pq-24',
    type: 'number_sequence',
    question: 'عدد گمشده در دنباله ۱۰، ۲۰، ...، ۴۰، ۵۰ چیست؟',
    options: [
      { id: 'a', text: '۳۰', isCorrect: true },
      { id: 'b', text: '۲۵', isCorrect: false },
      { id: 'c', text: '۳۵', isCorrect: false },
      { id: 'd', text: '۲۸', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'number_sequence',
    explanation: 'هر عدد ۱۰ واحد از قبلی بیشتر است: ۱۰، ۲۰، ۳۰، ۴۰، ۵۰.',
  },
  {
    id: 'pq-25',
    type: 'mental_calculation',
    question: 'حاصل ۹ × ۹ چیست؟',
    options: [
      { id: 'a', text: '۸۱', isCorrect: true },
      { id: 'b', text: '۷۹', isCorrect: false },
      { id: 'c', text: '۸۲', isCorrect: false },
      { id: 'd', text: '۹۱', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 5,
    difficulty: 'easy',
    category: 'multiplication',
    explanation: '۹ × ۹ = ۸۱. ترفند: رقم دهگان = ۹-۱=۸، رقم یکان = ۱۰-۹=۱. پس ۸۱.',
  },
];

// ─── Practice Exam Questions (Harder) ────────────────────

export const practiceQuestions: ExamQuestion[] = [
  {
    id: 'prq-1',
    type: 'mental_calculation',
    question: 'حاصل ۴۷ + ۵۶ + ۲۳ چیست؟',
    options: [
      { id: 'a', text: '۱۲۶', isCorrect: true },
      { id: 'b', text: '۱۱۶', isCorrect: false },
      { id: 'c', text: '۱۳۶', isCorrect: false },
      { id: 'd', text: '۱۲۵', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'medium',
    category: 'addition',
    explanation: '۴۷+۵۶=۱۰۳، سپس ۱۰۳+۲۳=۱۲۶.',
  },
  {
    id: 'prq-2',
    type: 'mental_calculation',
    question: 'حاصل ۱۰۰۰ - ۴۷۳ چیست؟',
    options: [
      { id: 'a', text: '۵۲۷', isCorrect: true },
      { id: 'b', text: '۵۳۷', isCorrect: false },
      { id: 'c', text: '۴۲۷', isCorrect: false },
      { id: 'd', text: '۶۲۷', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'hard',
    category: 'subtraction',
    explanation: 'مکمل ۱۰: ۹-۴=۵، ۹-۷=۲، ۱۰-۳=۷. نتیجه: ۵۲۷.',
  },
  {
    id: 'prq-3',
    type: 'mental_calculation',
    question: 'حاصل ۲۵ × ۴ چیست؟',
    options: [
      { id: 'a', text: '۱۰۰', isCorrect: true },
      { id: 'b', text: '۹۰', isCorrect: false },
      { id: 'c', text: '۸۰', isCorrect: false },
      { id: 'd', text: '۱۱۰', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'medium',
    category: 'multiplication',
    explanation: '۲۵×۴=۱۰۰. ترفند: ۲۵×۴ همیشه ۱۰۰ است.',
  },
  {
    id: 'prq-4',
    type: 'abacus_reading',
    question: 'در چرتکه دهگانی، عدد ۵۰۵ چگونه نمایش داده می‌شود؟',
    options: [
      { id: 'a', text: 'صدگان: ۵ بالا، دهگان: صفر، یکان: ۵ بالا', isCorrect: true },
      { id: 'b', text: 'صدگان: ۵ پایین، دهگان: صفر، یکان: ۵ پایین', isCorrect: false },
      { id: 'c', text: 'صدگان: ۱ پایین، دهگان: صفر، یکان: ۵ بالا', isCorrect: false },
      { id: 'd', text: 'صدگان: ۵ بالا، دهگان: ۵ بالا، یکان: صفر', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'medium',
    category: 'abacus_reading',
    explanation: '۵۰۵ = صدگان: مهره بالایی(۵)، دهگان: صفر، یکان: مهره بالایی(۵).',
  },
  {
    id: 'prq-5',
    type: 'mental_calculation',
    question: 'حاصل ۱۵ × ۶ چیست؟',
    options: [
      { id: 'a', text: '۹۰', isCorrect: true },
      { id: 'b', text: '۸۰', isCorrect: false },
      { id: 'c', text: '۸۵', isCorrect: false },
      { id: 'd', text: '۹۵', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'medium',
    category: 'multiplication',
    explanation: '۱۵×۶ = (۱۰×۶=۶۰) + (۵×۶=۳۰) = ۹۰.',
  },
  {
    id: 'prq-6',
    type: 'mental_calculation',
    question: 'حاصل ۲۰۰ - ۸۷ چیست؟',
    options: [
      { id: 'a', text: '۱۱۳', isCorrect: true },
      { id: 'b', text: '۱۲۳', isCorrect: false },
      { id: 'c', text: '۱۰۳', isCorrect: false },
      { id: 'd', text: '۱۳۳', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'medium',
    category: 'subtraction',
    explanation: '۲۰۰-۸۷: ابتدا ۲۰۰-۱۰۰=۱۰۰، سپس ۱۰۰+۱۳=۱۱۳.',
  },
  {
    id: 'prq-7',
    type: 'mental_calculation',
    question: 'حاصل ۳ × ۴ + ۸ ÷ ۲ چیست؟',
    options: [
      { id: 'a', text: '۱۶', isCorrect: true },
      { id: 'b', text: '۱۴', isCorrect: false },
      { id: 'c', text: '۲۰', isCorrect: false },
      { id: 'd', text: '۱۰', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'hard',
    category: 'mixed',
    explanation: 'ابتدا ضرب و تقسیم: ۳×۴=۱۲، ۸÷۲=۴. سپس جمع: ۱۲+۴=۱۶.',
  },
  {
    id: 'prq-8',
    type: 'number_sequence',
    question: 'عدد بعدی در دنباله ۱، ۱، ۲، ۳، ۵، ۸، ۱۳، ... چیست؟',
    options: [
      { id: 'a', text: '۲۱', isCorrect: true },
      { id: 'b', text: '۲۰', isCorrect: false },
      { id: 'c', text: '۱۸', isCorrect: false },
      { id: 'd', text: '۲۶', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'hard',
    category: 'number_sequence',
    explanation: 'دنباله فیبوناچی: هر عدد = مجموع دو عدد قبلی. ۸+۱۳=۲۱.',
  },
  {
    id: 'prq-9',
    type: 'mental_calculation',
    question: 'حاصل ۹۹ + ۹۹ چیست؟',
    options: [
      { id: 'a', text: '۱۹۸', isCorrect: true },
      { id: 'b', text: '۱۸۸', isCorrect: false },
      { id: 'c', text: '۲۰۸', isCorrect: false },
      { id: 'd', text: '۱۸۹', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'medium',
    category: 'addition',
    explanation: '۹۹+۹۹ = ۱۰۰+۱۰۰-۲ = ۱۹۸.',
  },
  {
    id: 'prq-10',
    type: 'mental_calculation',
    question: 'حاصل ۱۱ × ۱۱ چیست؟',
    options: [
      { id: 'a', text: '۱۲۱', isCorrect: true },
      { id: 'b', text: '۱۱۱', isCorrect: false },
      { id: 'c', text: '۱۳۱', isCorrect: false },
      { id: 'd', text: '۱۲۲', isCorrect: false },
    ],
    correctAnswer: 'a',
    points: 10,
    difficulty: 'medium',
    category: 'multiplication',
    explanation: '۱۱×۱۱=۱۲۱. ترفند: ۱۱ × هر عدد دو رقمی = مجموع ارقام در وسط.',
  },
];

// ─── Exams ────────────────────────────────────────────────

export const sampleExams: Exam[] = [
  {
    id: 'exam-placement',
    title: 'آزمون تعیین سطح',
    description: 'این آزمون برای تعیین سطح دانش‌آموز در چرتکه و حساب ذهنی طراحی شده است. بر اساس نتیجه، دوره مناسب پیشنهاد می‌شود.',
    type: 'placement',
    level: 'beginner',
    questions: placementQuestions,
    duration: 20,
    totalScore: 125,
    passingScore: 60,
  },
  {
    id: 'exam-practice-1',
    title: 'آزمون تمرینی - محاسبات ذهنی',
    description: 'آزمون تمرینی برای تقویت مهارت‌های محاسبه ذهنی شامل جمع، تفریق و ضرب.',
    type: 'practice',
    level: 'intermediate',
    questions: practiceQuestions,
    duration: 15,
    totalScore: 100,
    passingScore: 50,
  },
];

// ─── Initialize Sample Data ──────────────────────────────

export function initializeSampleData(): void {
  if (typeof window === 'undefined') return;

  // Check if data already initialized
  const initialized = localStorage.getItem('vira_data_initialized');
  if (initialized) return;

  // Save sample data
  localStorage.setItem('vira_leads', JSON.stringify(sampleLeads));
  localStorage.setItem('vira_students', JSON.stringify(sampleStudents));
  localStorage.setItem('vira_referrals', JSON.stringify(sampleReferrals));

  // Save sample exam results for some students
  const sampleResults = [
    {
      examId: 'exam-placement',
      examTitle: 'آزمون تعیین سطح',
      examType: 'placement' as const,
      score: 105,
      maxScore: 125,
      percentage: 84,
      passed: true,
      completedAt: '2024-11-15T14:30:00Z',
      duration: 960,
    },
    {
      examId: 'exam-practice-1',
      examTitle: 'آزمون تمرینی - محاسبات ذهنی',
      examType: 'practice' as const,
      score: 80,
      maxScore: 100,
      percentage: 80,
      passed: true,
      completedAt: '2024-11-20T16:00:00Z',
      duration: 780,
    },
    {
      examId: 'exam-placement',
      examTitle: 'آزمون تعیین سطح',
      examType: 'placement' as const,
      score: 95,
      maxScore: 125,
      percentage: 76,
      passed: true,
      completedAt: '2024-09-10T10:00:00Z',
      duration: 1100,
    },
  ];
  localStorage.setItem('vira_student_results', JSON.stringify(sampleResults));

  // Mark as initialized
  localStorage.setItem('vira_data_initialized', 'true');
}
